### ISSUE TITLE
standard parameters for deconvolution

### ISSUE THREAD

**Issue by RienLeuvenink** [mobiusklein/mzdeisotope#1]
Hi, 

I am trying to integrate mzdeistope in my analysis pipeline for deconvoluting middle down spectra of antibodies. Now I've got it working but I was wondering if you can give me some recommendations for 'standard parameters'/starting points for the high level API (deconvolute_peaks function). I've browsed through the python documentation and managed to come up with some numbers but not everything is completely clear to me. 

Many thanks in advance!
Rien

**Comment by mobiusklein** [comment]
Hello,

By Python documentation, you were reading about https://github.com/mobiusklein/ms_deisotope? `ms_deisotope` and `mzdeisotope` use the same core algorithm, but they're not actually linked. `mzdeisotope` is still a work in progress as all the parts get stress-tested and I haven't written any Python bindings for it yet. `mzdeisotope` is also missing a lot of features `ms_deisotope` has.

Choosing parameters for deconvolution is different for MS1 and MS2, depends upon the signal characteristics of your instrument (e.g. TOF vs Orbitrap), and the trade-off between sensitivity and specificity + runtime. For example, you might not have efficient fragmentation in MS2 so you prefer to accept more noise solutions (peaks that lack strong isotopic patterns) because the real isotopic patterns in the same score range will be more likely to be matched later than the noisy ones. Conversely, you might want to be conservative about how many MS1 solutions you accept because they take more work to filter through.

Suggestions for larger ions:
- Use the [`Peptide`](https://docs.rs/mzdeisotope/latest/mzdeisotope/isotopic_model/enum.IsotopicModels.html#variant.Peptide) isotopic model, it is the Senko Averagine formula. 
- Use `error_tolerance` = `Tolerance::PPM(20.0)`. The algorithm only works with high resolution MS so there's no point going higher.
- Set your charge range based upon your familiarity with your data, or when in doubt go high and then enable `use_quick_charge` = `true` and let the 
- Scoring and Filtering:
   - For MS1, use the [`PenalizedMSDeconv`](https://docs.rs/mzdeisotope/latest/mzdeisotope/scorer/struct.PenalizedMSDeconvScorer.html) with an `error_tolerance` of 0.02 and a `penalty_factor` of 1.0 or 2.0, and a [`MaximizingFitFilter`](https://docs.rs/mzdeisotope/latest/mzdeisotope/scorer/struct.MaximizingFitFilter.html) with a threshold between 10.0 and 20.0.
    - For MS2, use the same, but lower the threshold to between 5.0 and 10.0.
 - For `max_missed_peaks`, choose 1 or 2 for MS1, and 1 for MS2
 - For isotopic pattern generation:
   - Use `truncate_after` = 0.95 for MS1 and 0.8 for MS2. Alternatively, you can set this to 0.999 and set `incremental_truncation` to those values and let the algorithm try all possible configurations between those, but I haven't tested this extensively at scale. This controls how much of the complete isotopic pattern to try to match. Some truncation is necessary because isotopic patterns may get cut off by noise filtering or by the instrument (e.g. Orbitrap denoising), and missing peaks penalize the algorithm.
   - Use `ignore_below` = 0.001. This is the default.
   - Use `charge_carrier` = `PROTON`. This is the default
 - `use_quick_charge` is generally good to set to `true`, but if your monoisotopic peak is not detectable, then the algorithm will probably fail to select the correct charge.

I'll add more documentation at some point soon. Please feel free to ask more questions if this didn't help.

**Comment by RienLeuvenink** [comment]
I was indeed referring to the ms_deisotope github. Many thanks for your help this helped me a ton
